sfObjectGuardRememberKey:
  actAs:  [Timestampable]
  columns:
    id:
      type:           integer(4)
      primary:        true
      autoincrement:  true
    user_id:
      type:           integer(4)
    remember_key:     string(32)
    ip_address:
      type:           string(50)
      primary:        true
  relations:
    User:
      class:          sfObjectGuardUser
      local:          user_id
      foreignAlias:   RememberKeys
      onDelete:       CASCADE
  options:
    symfony:
      form:           false
      filter:         false
    collate:          utf8_unicode_ci
    charset:          utf8
