sfObjectGuardUserGroup:
  actAs:  [Timestampable]
  columns:
    id:
      type:           integer(4)
      primary:        true
      autoincrement:  true
    user_id:
      type:           integer(4)
      notnull:        true
    group_id:
      type:           integer(4)
      notnull:        true
  relations:
    User:
      class:          sfObjectGuardUser
      local:          user_id
      foreignType:    one
      onDelete:       CASCADE
    Group:
      class:          sfObjectGuardGroup
      local:          group_id
      foreignType:    one
      onDelete:       CASCADE
  options:
    symfony:
      form:           false
      filter:         false
    collate:          utf8_unicode_ci
    charset:          utf8
