sfObjectGuardActivationKey:
  actAs:  [Timestampable]
  columns:
    id:
      type:           integer(4)
      primary:        true
      autoincrement:  true
    user_id:
      type:           integer(4)
      notnull:        true
    key_type_id:
      type:           integer(4)
      notnull:        true
    activation_key:
      type:           string(32)
      notnull:        true
      unique:         true
    inviter_id:
      type:           integer(4)
    additional:
      type:           clob
  relations:
    User:
      class:          sfObjectGuardUser
      local:          user_id
      onDelete:       CASCADE
    Inviter:
      class:          sfObjectGuardUser
      local:          inviter_id
      onDelete:       CASCADE
    KeyType:
      class:          sfObjectGuardActivationKeyType
      local:          key_type_id
      onDelete:       CASCADE
